apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: tms
  labels: { app: identity-service }
spec:
  selector: { app: identity-service }
  ports:
    - { name: http, port: 8001, targetPort: http }
