apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tms
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/name: shell
  app.kubernetes.io/part-of: tms-frontend
images:
  - name: ghcr.io/handatransportation/shell
    newTag: placeholder
